#  ICOS Scaphandre
#  Copyright © 2022-2024 National and Kapodistrian University of Athens
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  This work has received funding from the European Union's HORIZON research 
#  and innovation programme under grant agreement No. 101070177.

image:
  name: menelaoszetas/icos_scaphandre
  tag: latest

port: 8080
nodePort: 30080

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 75m
    memory: 128Mi

scaphandre:
  command: prometheus
  args: {}
  extraArgs:
    containers: {}
#  rustBacktrace: '1'

# Run as root user to get proper permissions
userID: 0
groupID: 0

serviceMonitor:
  # Specifies whether ServiceMonitor for Prometheus operator should be created
  enabled: true
  interval: 1m
  # Specifies namespace, where ServiceMonitor should be installed
  namespace: icos-system
